# Default initial positions for cobot's ros2_control fake system

initial_positions:
  base_link__link1: 0
  link1__link2: 0
  link2__link3: 0
  link3__link4: 0
  link4__link5: 0
  link5__tcp_conector: 0
  tcp_conector__gripper_left: 0
  tcp_conector__gripper_right: 0